apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - image: nginxdemos/hello
        imagePullPolicy: IfNotPresent
        name: web-dev
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
