apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-storage-pv
  namespace: platform
  labels:
    usage: redis-storage-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: redis-storage-secret
    secretNamespace: platform
    shareName: redis
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
